Bastion authorization script

diff --git a/gp-download b/gp-download
--- a/gp-download
+++ b/gp-download
@@ -1,9 +1,15 @@
 #!/bin/bash
 
-SOURCE=/Volumes/Session0/DCIM
+VOLUME=$1
+
+if [ -z "$VOLUME" ]; then
+  echo "Please specify a volume"
+  exit 1
+fi
+
+SOURCE=/Volumes/$VOLUME/DCIM
 #DEST=/Volumes/HomeVideo
 DEST=/Users/steve/Desktop
-DRY=$1
 
 if [ ! -d "$SOURCE" ]; then
   echo "Source directory '$SOURCE' does not exist"
@@ -15,13 +21,6 @@ if [ ! -d "$DEST" ]; then
   exit 1
 fi
 
-if [ -z "$DRY" ]; then
-  echo "################################################"
-  echo "# DRY RUN ... Pass an argument to run for real #"
-  echo "################################################"
-  sleep 1
-fi
-
 find "$SOURCE" -type f \( -name "*.JPG" -or -name "*.MP4" \) -print0 | while IFS= read -r -d $'\0' FILE; do
   TIME=$(stat -f "%Sm" -t "%Y%m%d-%H%M%S" "$FILE")
   BASE=$(basename "$FILE")
@@ -29,12 +28,10 @@ find "$SOURCE" -type f \( -name "*.JPG" -or -name "*.MP4" \) -print0 | while IFS
   RANDOM=$(( ( RANDOM % 10000 ) + 1 ))
   NEW="$DEST/$TIME-$RANDOM.$EXT"
   echo "Copying $FILE to $NEW"
-  if [ ! -z "$DRY" ]; then
-    rsync --progress "$FILE" "$NEW"
-    if [ $? -ne 0 ]; then
-      echo "An error occured when copying the file"
-      exit 1
-    fi
+  rsync --progress "$FILE" "$NEW"
+  if [ $? -ne 0 ]; then
+    echo "An error occured when copying the file"
+    exit 1
   fi
 done
 
